name: "Valued Config Sync"
description: "Configure Valued projects from your repository"

branding:
  icon: refresh-cw
  color: yellow

runs:
  using: "node16"
  main: "scripts/action.js"

inputs:
  token:
    description: "Valued API token"
    required: true
  github-token:
    description: "Token for accessing the GitHub API"
    default: ${{ github.token }}
